POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Populate testi 3",
  "author": "mister",
  "url": "http://web",
  "likes": "3",
  "user": "5a859726efc0733ca11a2db4"
}